### ISSUE TITLE
Petition export in more useful format

### ISSUE THREAD

**Issue by thisisparker** [EFForg/action-center-platform#10]
Currently it's possible to export signatures from a petition-type action as a CSV that includes first_name, last_name, email, zipcode, country_code, and created_at. That's not super useful for actually delivering petitions. There should probably be an export tool that creates a file (can still be a CSV) with the full name, the city name, the state abbreviation, and the full country name. It would be nice, too, if that had a semantically meaningful name like $action_name-signature-export-YYYY-MM-DD.csv or something.

**Comment by thisisparker** [comment]
Another thing I just thought of: we sometimes need to go through and "weed" submissions by hand (like, if somebody puts in obviously fake values for their name that would be embarrassing to submit) so a direct PDF output is probably not ideal.

**Comment by TheNotary** [comment]
What's your feedback on this csv file:

(test_petition-exported_on-2015-10-06.csv)
```
full_name,email,city,state,country_code
John Doe,john@example.com,San Francisco,CA,United States of America
```

**Comment by thisisparker** [comment]
:+1: that looks beautiful.

**Comment by thisisparker** [comment]
One question, though! The last column is labeled "Country_code" but is the full country name, right?

**Comment by mfb** [comment]
For compatibility with our CRM, I would suggest: add postal code, split first name and last name, use ISO country code

**Comment by mfb** [comment]
Oh I see this is different from Parker's request above, so maybe have multiple columns for first name, last name, full name, country code, country name.

**Comment by thisisparker** [comment]
@mfb I hadn't been considering CRM compatibility. Does this CSV export actually interact with the CRM? I just need this tool for the actual petition output.

**Comment by TheNotary** [comment]
I just had a quick chat with mfb.  We do use the export to CSV button to upload them into CiviCRM, and it needs specific fields to be compliant.  

Can I ask you Parker, would you like to have your own button that says "Download Signatures (Presentable Form)" or perhaps a better name of your title that outputs the format I posted above?

**Comment by TheNotary** [comment]
Here's a mockup of what I have (the old CSV button is still there, and has unchanged functionality)

https://youtu.be/Af0oEiJJPXI

**Comment by mfb** [comment]
@thisisparker yeah we do sometimes download a CSV from action center and import it to CiviCRM (if we need to create a group/tag/whatever).  We don't really want to change the fields for this use case. Essentially what we're talking about here is adding a human-readable export to the existing machine-readable export.

**Comment by TheNotary** [comment]
feature added by 76a360c42eb3d23a68f676293e377fa6d17bd400
