### ISSUE TITLE
Add popover notice to the end of petition and email actions

### ISSUE THREAD

**Issue by maximillianh** [EFForg/action-center-platform#118]
Please add the following text to the end of petition and email actions:

> How will EFF use this information? (?)

When the user mouses over the question mark, they should see:

> We use this information to help you contact decision makers (e.g. Members of Congress) and their staff. We may work with other groups to assist in this action, such as sharing and jointly delivering petition signatures with a coalition partner. We may use Action Center information to assess the success of action campaigns and to improve the functionality and effectiveness of our site, and to allow you to see records of your activities. We, and our coalition partners, may publicize and share aggregate information about action campaigns, such as the number of people who participated in a particular location or region or through a type of action, as well as sharing or publicizing activity trends.

**Comment by mfb** [comment]
Just now pushed the CSS for this to the branch.
