### ISSUE TITLE
CSS is not applied to embedded actions on firefox

### ISSUE THREAD

**Issue by mfb** [EFForg/action-center-platform#124]
CSS for embedded actions apparently works on Chromium but not Firefox.  Not sure how long this has been the case.

**Comment by squiggy** [comment]
Can you provide a link that shows this happening?

**Comment by mfb** [comment]
for example, https://savecrypto.org or https://noglobalwarrants.org/

![chromium](https://cloud.githubusercontent.com/assets/3278/16243776/b8171594-37ad-11e6-8bb1-27a59d33e8c2.png)
![firefox](https://cloud.githubusercontent.com/assets/3278/16243777/b81bb9f0-37ad-11e6-856a-c5ba07c6e02a.png)

**Comment by mfb** [comment]
Ok just realized it's Privacy Badger. Somehow Privacy Badger is blocking CSS loading from www.eff.org on other sites :/   I'm not sure why/how because www.eff.org should have the DNT policy.

**Comment by mfb** [comment]
Cooper showed me how to manually nuke my Privacy Badger settings (a multistep process using Firefox extension debugger) and it's working now.

Hopefully this was only affecting a tiny number of people, and in any event the Firefox version of Privacy Badger is going to be rewritten, so I'm going to close this.
