### ISSUE TITLE
Get rid of Figaro

### ISSUE THREAD

**Issue by vbrown608** [EFForg/action-center-platform#166]
Secrets are all stored as environment variables in docker-compose.yml now. I think that means we can get rid of Figaro.

An update to the README's Secrets section will also be needed.

**Comment by vbrown608** [comment]
@Hainish do you agree?

**Comment by Hainish** [comment]
@vbrown608 it does seem a bit labyrinthine that we have our app configurations referenced in `docker-compose.yml`, `secrets.yml`, and `application.yml` (if it exists).

The main functionality that Figaro provides is allowing users to *either* specify configurations in `application.yml` *or* through the environment.  This may still be useful if you envision contributors that aren't familiar with docker being able to get their dev environment set up and make meaningful contributions.  This is the traditional development pattern for Ruby devs, using `rvm` on their local instance with a gitignore'd `secrets.yml` file.  Removing Figaro almost makes this more difficult, but it also reduces the complexity of the configuration setup.  It's your call, really.

**Comment by vbrown608** [comment]
Thanks @Hainish. That's a good point about non-docker users.

I'm not sure yet how much we should should support them. Right now my plan is to move non-docker setup (local, heroku, and prod) instructions out of the readme and onto a linked wiki page. But navigating application.yml seems to be a step more challenging. I imagine they would have to place their secrets directly in secrets.yml and then take care not to commit them.

The Figaro gem has no dependencies, so I think the only drawback is the confusion of tracing environment variables' path into the app. On the other hand, the non-docker users we're supporting might be imaginary.

**Comment by Hainish** [comment]
Also worth noting that this applies as much to `dev` as it does to `production`.  If someone downstream from this project wants to deploy in a VM instead of `docker`, it makes it more complicated.  One thing you could possibly do is just note that all configs have to be specified in the environment, regardless of if you're using `docker` or not.  That way, those running within a VM or bare metal would know they need to create some wrapper for the application which specifies these values.

**Comment by vbrown608** [comment]
@wioux and I discussed this. We are planning to switch from figaro to dotenv, and make a note suggesting that users set environment variables in a dotenv file if they choose not to use docker.

**Comment by Hainish** [comment]
Sounds like a good plan!
