### ISSUE TITLE
Run delayed jobs?

### ISSUE THREAD

**Issue by vbrown608** [EFForg/action-center-platform#169]
I used the delayed job gem to allow staff to upload large CSVs of institutions to a local organizing petition. 

I noticed we have lots of delayed jobs stored in the production database that are being created in `tweet_target.rb` to attach a twitter image. @Hainish, do you know if we should be running these? I assume so. 

In either case, we should add a delayed job worker to a our Docker setup and document delayed jobs for both the docker and non-docker case.

**Comment by wioux** [comment]
- Institutions import
- Twitter images
- Signature deduplication
- Congress update
