### ISSUE TITLE
Invalid regex in phone validation form fill

### ISSUE THREAD

**Issue by maximillianh** [EFForg/action-center-platform#174]
`form-validation.js:formatted:126Pattern attribute value ^((5\d[123467890])|(5[123467890]\d)|([2346789]\d\d))\-\d\d\d-\d\d\d\d$ is not a valid regular expression: Uncaught SyntaxError: Invalid regular expression: /^((5\d[123467890])|(5[123467890]\d)|([2346789]\d\d))\-\d\d\d-\d\d\d\d$/: Invalid escape`

This is preventing form-fills with valid phone numbers.

**Comment by vbrown608** [comment]
@maximillianh could you provide instructions for reproducing? what page are you seeing this on?

**Comment by vbrown608** [comment]
Nevermind, I see it now on https://act.eff.org/action/national-stop-tpp-call-in-day

**Comment by vbrown608** [comment]
Removing the escape characters (ie "\") seems to fix it. See http://stackoverflow.com/questions/36953775/firefox-error-unable-to-check-input-because-the-pattern-is-not-a-valid-regexp
