### ISSUE TITLE
Javascript cleanup (more)

### ISSUE THREAD

**Issue by wioux** [EFForg/action-center-platform#175]
Separate issues from #65 
- [x] Clean out inline `<script>` tags
- [x] Clean out global variables like [date_start and date_end](https://github.com/EFForg/action-center-platform/blob/master/app/views/admin/action_pages/_date_vars.html.erb), [petition_id](https://github.com/EFForg/action-center-platform/blob/master/app/views/tools/_petition.html.erb#L2), [welcome.js stuff](https://github.com/EFForg/action-center-platform/blob/master/app/assets/javascripts/application/welcome.js), etc.
- [ ] Standardize on templating framework (ejs and underscore are both used). Remove unnecessary templates, preferring rendered html.
- [x] Move third party js under vendor/assets

**Comment by k-stewart** [comment]
@wioux Should this be closed?
