### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by wioux** [EFForg/action-center-platform#177]
A few spots in the code ([1](https://github.com/EFForg/action-center-platform/blob/43eb4528b308755f4499b0f2506b69d44bd4a872/app/controllers/smarty_streets_controller.rb#L44), [2](https://github.com/EFForg/action-center-platform/blob/43eb4528b308755f4499b0f2506b69d44bd4a872/lib/smarty_streets.rb#L17), [3](https://github.com/EFForg/action-center-platform/blob/43eb4528b308755f4499b0f2506b69d44bd4a872/lib/civicrm.rb#L80)) `puts` error messages to stdout. Let's call `Rails.logger` instead.

**Comment by vbrown608** [comment]
Closed by #284
