### ISSUE TITLE
tools_controller email_target is using incorrect method for URL-encoding

### ISSUE THREAD

**Issue by mfb** [EFForg/action-center-platform#194]
apparently URI::escape is old and broken. it doesn't URL-encode commas, for example.  

This causes mailto: redirect using the default mail client to fail on Chrome browser.

It looks like we should be using http://ruby-doc.org/stdlib-1.9.3/libdoc/erb/rdoc/ERB/Util.html#method-c-url_encode for URL-encoding.

**Comment by mfb** [comment]
forgot to mention this is being tracked internally in https://redmine.eff.org/issues/9988 so when fixed we should close it there too

**Comment by wioux** [comment]
Fixed in #205.
