### ISSUE TITLE
Bug: the stats on a users show page are indicating fuzzy numbers

### ISSUE THREAD

**Issue by TheNotary** [EFForg/action-center-platform#22]
Check out Rainey's user/show page...

It states:  "you are in the 99th percentile"
action you've taken: x calls, y petitions, z emails. Total: 34"

where `x+y+z != 34`... not even remotely...

**Comment by vbrown608** [comment]
The total includes tweet actions, which aren't shown in the table. Seems like that's confusing - we could replace the total in the grid with a tweet count and let users some it up themselves if they really want to.

**Comment by vbrown608** [comment]
@jpt do you want to weigh in on this? You can see it at act.eff.org/account. If there's a nice-looking designerly way to have 5 numbers let's do that. Otherwise I've got a branch with my suggestion above.

**Comment by vbrown608** [comment]
mocked up a few options w/ help from @jpt - I think I like #2.

1. ![screenshot from 2016-10-27 18-03-29](https://cloud.githubusercontent.com/assets/1887071/19790859/f2896754-9c70-11e6-98ef-4e1128c87c6c.png)

2. ![screenshot from 2016-10-27 18-07-51](https://cloud.githubusercontent.com/assets/1887071/19790860/f289e134-9c70-11e6-82c4-243a4387b14d.png)

3. ![screenshot from 2016-10-27 18-08-33](https://cloud.githubusercontent.com/assets/1887071/19790858/f288ad1e-9c70-11e6-9a95-7bd8b08996af.png)

**Comment by hughillustration** [comment]
Nice!

I like options 2 & 3.

I wonder if the total shouldn’t be somehow highlighted — so that it’s clear it’s not just another number, and not just related to the column it appears under.

H.
