### ISSUE TITLE
Make twitter actions work without javascript OR add notice that javascript is required

### ISSUE THREAD

**Issue by mfb** [EFForg/action-center-platform#273]
Users of NoScript, Tor Browser or others with javascript disabled are unable to complete twitter actions, and also have no notice that they should enable javascript.

**Comment by wioux** [comment]
We could get our end working in a degraded fashion, but the twitter.com URL we open is completely blank without JS so... :\ I'm just gonna add a notice.

**Comment by vbrown608** [comment]
I think I remember seeing some no-js action where we provide a little text box with suggested text for users to copy and paste into twitter...that might be nice.
