### ISSUE TITLE
rss feed doesn't validate

### ISSUE THREAD

**Issue by lenazun** [EFForg/action-center-platform#297]
One of our user writes

> https://act.eff.org/action.atom
> I use an RSS aggregator on my site and this particular feed does not work.
> If you go to Feed Validator you can see why it doesn't work.

**Comment by mfb** [comment]
Weird, it looks like we made up our own elements? Instead of using standard ways to extend Atom.  We do need images for things like the mobile app,  we should just make sure we define them in a valid way.
