### ISSUE TITLE
For petitions, ignore repeat signatures based on email

### ISSUE THREAD

**Issue by Hainish** [EFForg/action-center-platform#3]
For petitions, we'd simply check if anyone with that email has signed before.  If so, ignore the signature and don't attempt to deliver an email.  This will reduce the risk of spam.

**Comment by mfb** [comment]
The one positive thing about not ignoring repeat signatures is that it's privacy protecting - if you enter someone's email address, the petition signature count will still increment, whether or not they already signed it.

**Comment by Hainish** [comment]
Good point @mfb, perhaps we should simply not send the repeat email, but log the signature.  We can then de-dupe as a rake task on a regular interval, which would be better for privacy.

**Comment by mfb** [comment]
The dedupe rake task sounds ideal, does anyone want to work on this? :)

**Comment by vbrown608** [comment]
@wioux's rake task is looking good! Now we just need to set it up to run at regular intervals.
