### ISSUE TITLE
problems sharing on facebook an action with a title containing apostrophes 

### ISSUE THREAD

**Issue by lenazun** [EFForg/action-center-platform#315]
For example
https://act.eff.org/action/don-t-let-congress-censor-the-internet

when linked on facebook, the title string gets cut off at the apostrophe

![facebook](https://user-images.githubusercontent.com/6117168/29984630-1da90e84-8f10-11e7-94d3-82060558addd.png)

ref https://redmine.eff.org/issues/14797

**Comment by vbrown608** [comment]
Haha the apostrophe strikes again!

**Comment by hughillustration** [comment]
I’m changing my name to Hugh D&#8217;Andrade.

H.

**Comment by wioux** [comment]
It looks like this was fixed (somehow). Closing but feel free to open again if it is still an issue.
