### ISSUE TITLE
return a more helpful error when trying to remove admin from an account that doesn't exist

### ISSUE THREAD

**Issue by lenazun** [EFForg/action-center-platform#317]
ref: https://redmine.eff.org/issues/14783
when trying to remove admin status from an account that doesn't exist, we return an unhelpful error. perhaps we could return a nicer one? I'm also changing the documentation to avoid this case.

**Comment by vbrown608** [comment]
Adding a bit more detail from the redmine ticket in case a volunteer would like to jump in:

When someone runs `rake users:remove_admin[me@example.org]` and me@example.com is not a recognized user, rails throws the following error: 

```
rake aborted!
NoMethodError: undefined method `admin=' for nil:NilClass
/opt/actioncenter/lib/tasks/users.rake:12:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => users:remove_admin
(See full trace by running task with --trace)
```

This should fail more gracefully.

**Comment by k-stewart** [comment]
https://github.com/EFForg/action-center-platform/pull/355

**Comment by k-stewart** [comment]
@lenazun See what you think of the fix.

**Comment by lenazun** [comment]
Looks great, thank you!
