### ISSUE TITLE
Radio styles are a little messed up

### ISSUE THREAD

**Issue by wioux** [EFForg/action-center-platform#322]
![action_center_radios](https://user-images.githubusercontent.com/6469642/30297130-8c5f8996-96fb-11e7-92f8-e006457d65e0.png)

https://act.eff.org/action/california-restore-our-online-privacy-rights

**Comment by squiggy** [comment]
I was able to fix this with `vertical-align: top`

**Comment by wioux** [comment]
The title of this issue is vague. Sorry. I meant the missing colors/check mark effect. They should look like this:

![action_center_radios2](https://user-images.githubusercontent.com/6469642/30297829-fef219f4-96fd-11e7-9104-2ef5d3bd134c.png)

**Comment by vbrown608** [comment]
Closed by #321
