### ISSUE TITLE
Subscription defaults on congressional actions

### ISSUE THREAD

**Issue by maximillianh** [EFForg/action-center-platform#330]
The mailing list subscription field should be checked/TRUE by default for congressional actions only.  If there is a partner on the congressional action, their subscription should also be checked by default.  

On Twitter, email, call, and petition actions, mailing list subscription should remain unchecked by default.

**Comment by vbrown608** [comment]
Could you say more about the reasons for this? It seems like such a subtle difference between the action types might be confusing for people who aren't already aware of it.

If it's for a single campaign, maybe we could make this change and then roll it back when the campaign is over. Alternatively, we could make this a configurable setting on all actions.
