### ISSUE TITLE
Sen Feinstein contact not working

### ISSUE THREAD

**Issue by lenazun** [EFForg/action-center-platform#352]
ref https://redmine.eff.org/issues/16113
This is also happening on democracy.io
I checked her form but it seems to be the same she had last year

![feinstein](https://user-images.githubusercontent.com/6117168/35167253-9e24dc3e-fd09-11e7-9d2e-e49fef365a1a.png)

**Comment by wioux** [comment]
Fixed in https://github.com/EFForg/phantom-of-the-capitol/pull/131
