### ISSUE TITLE
Update contact preferences form

### ISSUE THREAD

**Issue by maximillianh** [EFForg/action-center-platform#404]
We should route users to [https://supporters.eff.org/update-your-preferences](https://supporters.eff.org/update-your-preferences), passing cid and the checksum to that form.

**Comment by vbrown608** [comment]
It looks like the checksum needs to be generated by civicrm. We could add an endpoint to the supporters API to get one, but at that point it seems easier to just make an endpoint that authenticates with the supporters API key and redirects to the the correct form with checksum. I'm going to proceed that way unless I'm missing something about the way checksums work.
