### ISSUE TITLE
Password requirements should match for new passwords and reset passwords

### ISSUE THREAD

**Issue by lenazun** [EFForg/action-center-platform#456]
From Starchy:
(https://redmine.eff.org/issues/16388#change-84925)

This ticket is for us to check that the password requirements are the same when registering a new account and when resetting your password, as a regular user.

**Comment by lenazun** [comment]
if you fix it, can you comment on the redmine ticket?

**Comment by wioux** [comment]
Splitting this into #470 and #471.
