### ISSUE TITLE
General question - not really an issue

### ISSUE THREAD

**Issue by hugoroy** [EFForg/action-center-platform#488]
Hello! I wrote an email but didn't get a reply :-)

My question is whether this platform could be reused by other non-governmental organisations, for a similar action center for their own campaigns.

Do you think EFF's platform could be reused by other orgs easily, or is the code so EFF-specific at the moment that you advise against it? Would you be interested in pull requests to allow the platform to be localized for other languages?

Thanks for your time.

Best regards,
Hugo

**Comment by lenazun** [comment]
Hi Hugo
I believe the platform could be reused by other organizations, with limited functionality.  It would also require a bit of work to separate what is EFF specific.
At the moment we're starting a re-design project for the summer that will change the look and feel and the functionality of the platform, so I would wait to localize once the project is done. 
Thank you for your message!

Lena

**Comment by hugoroy** [comment]
Thanks for your response, Lena.

Feel free to reach out if you'd like external contributions in this 
process. I am involved in several organisations which may be interested 
in this (ToS;DR, Free Software Foundation Europe, and Data Rights). And 
I hope the design will include localization features :-)

**Comment by hugoroy** [comment]
Hello @lenazun - any news on the redesign project? How is this going?
