### ISSUE TITLE
Allow test submissions of congress message actions

### ISSUE THREAD

**Issue by vbrown608** [EFForg/action-center-platform#526]

**Comment by vbrown608** [comment]
Chatted with Kim a bit about this ticket. There are two goals:
1. Preview the thank you e-mail. This might be added to the admin UI separately.
2. Test the the action is not broken. This is a little tricky - it's hard to test that submission is working without actually submitting. Some possibilities:
  * We could add a test mode to congress_forms that either uses CWC test mode or completes a full fill short of submitting
  * We could add a test mode to the action center doesn't submit to congress_forms_api
  * We could improve logging to Sentry, try to eliminate as much Sentry noise and possible, and monitor it more closely, as a different way to increase confidence.

**Comment by wioux** [comment]
Support is already (secretly) there for the first idea to address (2) -- you can trigger it by adding `test=1` as a query param to the action center page. For user friendliness though, I'm thinking we could show a second submit button to admin users?

![Screenshot_2019-06-12_16-23-45](https://user-images.githubusercontent.com/6469642/59393292-cc2d2200-8d2f-11e9-964f-682b68c713a1.png)

**Comment by vbrown608** [comment]
Awesome! Sounds good to me.
