### ISSUE TITLE
reject postal code longer than 12 characters

### ISSUE THREAD

**Issue by mfb** [EFForg/action-center-platform#6]
This would work around a bug in CiviCRM where a contact import fails if the postal code is longer than 12 characters.

**Comment by mfb** [comment]
(This bug can be reproduced on petition actions - not sure about other types of actions)

**Comment by TheNotary** [comment]
Approached in commit:  https://github.com/TheNotary/action-center-platform/commit/0234bd1c5d044865ae140203e00ce86ef8fd9ce1

I'm not set up to do manual testing yet, btw :cold_sweat:
