### ISSUE TITLE
add CORS header to action.atom

### ISSUE THREAD

**Issue by mfb** [EFForg/action-center-platform#60]
The mobile app needs an `Access-Control-Allow-Origin: *` header on https://act.eff.org/action.atom

I'm not sure off the top of my head the correct way to add such headers to end points. maybe faster for @TheNotary to patch this in?

**Comment by TheNotary** [comment]
The app accepts an array of domains to add CORS privs to, will that work?  If that won't work I can add the wildcard to requests for `/action.atom`.

**Comment by mfb** [comment]
I think anyone using this software will want the atom feed to be consumable by javascript running on any site.  So it could be baked in to the atom feed endpoint.

**Comment by TheNotary** [comment]
closing per #63
