### ISSUE TITLE
Congress topics link doesn't work

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#605]
In the admin dashboard, the Congress Topics link does not work
<img width="220" alt="Screen Shot 2019-08-08 at 2 04 26 PM" src="https://user-images.githubusercontent.com/8976353/62737787-8dd97980-b9e5-11e9-8fcc-6f8caf35fbd5.png">
.

**Comment by wioux** [comment]
Just deployed the fixes for congress topics to staging.
