### ISSUE TITLE
Main page style fixes

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#613]
Some style fixes from Hugh for the Main page of the Action Center:
1. Close space above tag line by 50%
2.  For the main featured article, align category & title with top of image
3. Take action text on button should be on 1 line
4. Reduce width of margins between columns by 1/3 (this might be hard, OK if not possible)
5. Reduce space above “See All Our Campaigns” by 50%

6. Main page: Left margin is inconsistent as window reduces 
— sometimes the left edge touches the edge of the window. 
— On tablet view, the logo and image do not align.

**Comment by lschatzkin** [comment]
For #3, I'm seeing the action text on one line already.

**Comment by krcarlson** [comment]
Weird, not on my end. 
<img width="1124" alt="Screen Shot 2019-08-13 at 12 34 33 PM" src="https://user-images.githubusercontent.com/8976353/62971444-c0f58180-bdc6-11e9-8627-3bb0f7b58528.png">
