### ISSUE TITLE
Main page: category not appearing above title

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#614]
Action category should appear above the action title on the main page 
<img width="811" alt="Screen Shot 2019-08-13 at 10 25 45 AM" src="https://user-images.githubusercontent.com/8976353/62962906-c4800d00-bdb4-11e9-94d0-366635bc5678.png">
<img width="740" alt="Screen Shot 2019-08-13 at 10 25 49 AM" src="https://user-images.githubusercontent.com/8976353/62962908-c5b13a00-bdb4-11e9-87cf-37e693bb5c27.png">

**Comment by lschatzkin** [comment]
I just realized that I don't have an admin login on staging, but I think it's not showing because no category was chosen for those actions.
