### ISSUE TITLE
Action page style fixes

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#615]
Here are Action page style fixes from Hugh:

1. Left margin is inconsistent as window reduces 
— sometimes the left edge touches the edge of the window. 
— On tablet view, the logo and image do not align.

2. Take Action text not reading in League Gothic

3. Title is intended to be full page width, with image and Action box aligning beneath it.

4. Submit Your Message button text not centered

5. Let’s remove red outline on Question Mark box. These should be smaller by 50% and square.

6. The tabbed number system at the top of the action box is not appearing.

7. The text and page flow appears to be different from wireframes

8. "Customize your message” text should not be italicized.

9. “How will EFF use this information?” should not be heading weight (I believe that’s corrected in the updated text)

9. Learn more is not revealing the related content (blog links etc)

**Comment by lschatzkin** [comment]
For (2) I'm not sure why that is happening as it is not a  problem in my sandbox. I think someone with web7 access needs to check to make sure the font file is on the server. No idea why it wouldn't be, but that's my guess as to the problem.

**Comment by lschatzkin** [comment]
I'm confused by (3), that isn't what I am seeing in the mockup, I'm seeing the title on the left.
![Screenshot from 2019-08-13 15-34-53](https://user-images.githubusercontent.com/852512/62982085-f5296c00-bddf-11e9-90b7-b2f4ef43737b.png)

**Comment by lschatzkin** [comment]
(1) is fixed in PR #617

**Comment by lschatzkin** [comment]
Putting (10) in a separate ticket
