### ISSUE TITLE
Thank you box on Congress Action needs re-styling

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#618]
The thank you page on Congress Actions needs re-styling. May be a bad merge?
<img width="491" alt="Screen Shot 2019-08-14 at 11 30 23 AM" src="https://user-images.githubusercontent.com/8976353/63047693-ccf64780-be89-11e9-97c3-0d4cfd25adc4.png">

**Comment by lschatzkin** [comment]
what the heck? Yep, that's a bad merge!
