### ISSUE TITLE
Edits to Admin sharing page

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#621]
1. "Share Message" field should be first (above "Title" field)
2. Add text to parenthesis in "Title" that says:
"(FB = 100chars, TWTR = 70chars. If left blank, this will default to the Title of your Action)" 
3. "Open Graph Image" should be called "Social Media Card Image" and default to the image that was uploaded for the action under "Images"

**Comment by wioux** [comment]
Just deployed fixes to staging.
