### ISSUE TITLE
Display Action summary on homepage

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#626]
Action summaries are missing from actions on the homepage
<img width="1044" alt="Screen Shot 2019-08-14 at 12 26 54 PM" src="https://user-images.githubusercontent.com/8976353/63049996-dfbf4b00-be8e-11e9-82e2-46f50b616eec.png">

**Comment by lschatzkin** [comment]
Oh, I didn't see the summaries on the mockup, so I thought we were removing them. I'll put them back in.
