### ISSUE TITLE
Review styles for embedded actions

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#658]
Peter says: 
Styles for embedded actions need review since the page structure/theme has changed – not sure whether this affects anything but https://www.eff.org/reclaim-invention/pledge

**Comment by lschatzkin** [comment]
This is caused by some css in kittens for reclaim invention, so I'm fixing it there

**Comment by lschatzkin** [comment]
PR can be found here: https://gitlab.eff.org/ed/kittens/merge_requests/976
