### ISSUE TITLE
Remove hover color on action summary text

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#669]
Currently, the Action summary text turns gray on hover. Please remove that.
<img width="1060" alt="Screen Shot 2019-08-29 at 3 06 01 PM" src="https://user-images.githubusercontent.com/8976353/63981258-2efea180-ca73-11e9-9895-7508c56b9349.png">

**Comment by lschatzkin** [comment]
There a hover state on the action page index so we should probably either have a hover state on both pages or neither. I think we should have it, but no strong preference.
![Screenshot from 2019-08-30 12-03-07](https://user-images.githubusercontent.com/852512/64045493-4a72b680-cb1e-11e9-9f6e-20096f11b366.png)

**Comment by krcarlson** [comment]
Currently, the hover state on the homepage just applies to the action summary text, so I'd say let's apply it to the title, banner, and issue tag (and remove it from the summary text) so it matches the index page.

**Comment by lschatzkin** [comment]
Sound good, doing it now.
