### ISSUE TITLE
Match "Learn More" text to Summary text style

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#686]
On an action page, the "Learn More" text should match the style of the summary text. Currently it's smaller and indented. 
<img width="746" alt="Screen Shot 2019-09-09 at 9 01 38 AM" src="https://user-images.githubusercontent.com/8976353/64547190-f49dcb80-d2e0-11e9-8dc6-ef3d24ecd89b.png">

**Comment by esoterik** [comment]
resolved in #687
