### ISSUE TITLE
Fix Guided flow numbered tabs

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#689]
Step 1 on the guided action 1-4 tabs stays highlighted as a user progresses through the action steps. <img width="413" alt="Screen Shot 2019-09-09 at 10 40 44 AM" src="https://user-images.githubusercontent.com/8976353/64553667-9f68b680-d2ee-11e9-84e6-504907379bc8.png">

**Comment by lschatzkin** [comment]
I think this got messed up in a merge, but I also think that this will be fixed in the work that Syd is currently doing on congress actions.

**Comment by esoterik** [comment]
yeah i'm doing a lot of work on this section right now!

**Comment by lschatzkin** [comment]
Cool!
