### ISSUE TITLE
Add eff.org to hamburger menu

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#691]
Let's add "eff.org" to the hamburger menu on the homepage.
<img width="312" alt="Screen Shot 2019-09-09 at 11 28 27 AM" src="https://user-images.githubusercontent.com/8976353/64556766-f5d8f380-d2f4-11e9-85ca-8a595425e0e9.png">

**Comment by krcarlson** [comment]
Let's also add a link to all EFF campaigns in the hamburger menu. The link would say "EFF Campaigns" 

Menu order should be: 
EFF Campaigns
Register
Login
eff.org

EFF Campaigns should link to the EFF Campaigns page: https://act.staging.eff.org/action

**Comment by esoterik** [comment]
resolved in #695
