### ISSUE TITLE
Summary and Action Box shouldn't extend past graphic on mobile

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#698]
The summary and Read More text, and Take Action box shouldn't extend past the Action graphic on mobile. 

Examples:
https://act.staging.eff.org/action/tell-congress-we-don-t-need-more-bad-patents-8941b5c6-5bb1-4d93-9ca1-a2da87c4458e

https://act.staging.eff.org/action/don-t-let-congress-undermine-our-online-privacy-3b478b04-bdb4-4ad0-8138-67f3afde69eb

<img width="738" alt="Screen Shot 2019-09-09 at 1 37 05 PM" src="https://user-images.githubusercontent.com/8976353/64564772-2e81c880-d307-11e9-9c30-ff85f7f3ce01.png">

**Comment by lschatzkin** [comment]
@krcarlson The problem is those images are small. We could force them to expand to 100% but they will be blurry.

**Comment by krcarlson** [comment]
Ah that makes sense. Let's just leave them then. This shouldn't be a problem with new actions.
