### ISSUE TITLE
Center Donate button on Call Action Thank You

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#699]
Center Donate button on Call Action Thank You page (and switch out donate button so it has white text)
<img width="361" alt="Screen Shot 2019-09-09 at 1 45 27 PM" src="https://user-images.githubusercontent.com/8976353/64565270-43129080-d308-11e9-877e-8e861f6563b8.png">

**Comment by lschatzkin** [comment]
This is fixed in #688
