### ISSUE TITLE
Add padding to Take Action button on homepage

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#703]
Hugh says: 
The button on the main front page action needs padding. I'm not sure, in terms of rem, how large it should be. .5 rem? I've attached a snapshot. I'd like that fixed before launch since it's a very visible item. 

![action-front-page-button](https://user-images.githubusercontent.com/8976353/64570020-12d0ef00-d314-11e9-80aa-d70c2448d837.jpg)

**Comment by lschatzkin** [comment]
@k-stewart I added 1rem to the right & left, can @hughillustration take a look?
![Screenshot from 2019-09-09 15-20-25](https://user-images.githubusercontent.com/852512/64570447-80314f80-d315-11e9-9568-3e650edb81e3.png)

**Comment by lschatzkin** [comment]
Hmm, maybe some padding above the button too.
