### ISSUE TITLE
Wrap Learn More text around Related Content

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#722]
Can we wrap the Learn More text around the Related content? <img width="569" alt="Screen Shot 2019-09-11 at 2 47 02 PM" src="https://user-images.githubusercontent.com/8976353/64738094-34acac00-d4a3-11e9-89e9-ed2dcec98c8b.png">

**Comment by lschatzkin** [comment]
Do you mean not have it in two columns?

**Comment by krcarlson** [comment]
Yeah, and not a launch blocker.
