### ISSUE TITLE
Bottom of 'y' cut off in email campaigns

### ISSUE THREAD

**Issue by TheNotary** [EFForg/action-center-platform#73]
```
On FF, Linux Mint
  For call campaigns
    On my screen it looks like it reads "Email vour representatives"
```

https://act.eff.org/action/tell-congress-to-vote-no-on-the-tpp

The height can be changed to fix this, I wonder how the other browsers/OSes render...

**Comment by vbrown608** [comment]
I used to be able to reproduce this on Ubuntu in Firefox (but not Chrome). Now I can't produce on either. Browserstack doesn't support offer and Linux distros.
