### ISSUE TITLE
Admin: Save removes paragraphs

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#746]
When admin create a new action (in this case, a congress message) and click "Save" on the last step  (Thank you page), the paragraphs/line breaks are removed from the Summary and Description text when you view it. It seems like you can go back and edit the action to add back in the paragraphs, but it's a pain.
<img width="834" alt="Screen Shot 2019-09-19 at 10 05 57 AM" src="https://user-images.githubusercontent.com/8976353/65265314-7c47bf00-dac5-11e9-94d3-bb1f1935aaeb.png">

**Comment by lschatzkin** [comment]
Please confirm:  this only happens from the Thank You page save button, not the one in the left sidebar.

**Comment by krcarlson** [comment]
Just tested it again, and it looks like it happens in both instances. It happened when I clicked Save in the side bar and has also happened after clicking Save on the Thank You page.

**Comment by lschatzkin** [comment]
Okay, it only happens for me on the thank you page, so thanks for checking that.

**Comment by esoterik** [comment]
this is [a bug](https://github.com/OscarGodson/EpicEditor/issues/308) in epic editor. we should resolve this by replacing it with a different editor (perhaps CKedtior?)
