### ISSUE TITLE
Autopopulate campaign tag with Action title

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#753]
The Campaign tag used to auto populate with the Action title (but could be modified if needed). Currently, it doesn't auto fill anymore, which means congressforms can't count up the number of messages sent for that campaign. Let's populate that field again. 

![Screen Shot 2019-09-26 at 10 31 20 AM](https://user-images.githubusercontent.com/8976353/65717282-c85eaa80-e055-11e9-9541-8c0ae92d9f76.png)

**Comment by esoterik** [comment]
closed in #766
