### ISSUE TITLE
"Email friends" URLs in thank you emails seem to be escaped incorrectly

### ISSUE THREAD

**Issue by thisisparker** [EFForg/action-center-platform#77]
At least in Thunderbird, the escaping puts + signs between each word instead of the expected spaces. I think it's defined in the [action page helper](https://github.com/EFForg/action-center-platform/blob/5a07c3dbd2bc385791aed23d5290d904bcd052de/app/helpers/action_page_helper.rb#L33-L38), but I don't know enough about the escaping there to know what's wrong.

**Comment by TheNotary** [comment]
In this app, the `t()` calls are for translate, which do lookups against https://github.com/EFForg/action-center-platform/blob/master/config/locales/en.yml

Is this an urgent one, Parker?

**Comment by mfb** [comment]
Spaces in URL components should be encoded as %20 rather than +

We fixed this bug in our PHP sites by calling rawurlencode() rather than urlencode() - not sure what the ruby fix is...

**Comment by vbrown608** [comment]
@wioux fixed this with #205 :smiley:
