### ISSUE TITLE
Remove double pagination from petitions

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#795]
The pagination on petition actions seems to have a bug. The numbers show up twice. 

e.g., https://act.eff.org/action/about-face
![Screen Shot 2019-12-11 at 6 45 49 PM](https://user-images.githubusercontent.com/8976353/70737341-21d68d00-1cc7-11ea-8ebd-66a069f298d7.png)

**Comment by wioux** [comment]
Fixed in 2a8e1b2a397373b3edbbc717364c1c33e0f7f8fa.
