### ISSUE TITLE
Signup flow is broken

### ISSUE THREAD

**Issue by sinak** [EFForg/action-center-platform#8]
After you try to register for an account, the site redirects you to the homepage. This must be a regression that's happened relatively recently, as it definitely wasn't the case before.

The "confirm my account" message is sent to the user, but they should be notified to look for an email in their inbox and that isn't happening.

**Comment by Hainish** [comment]
Fixed! Using javascript to display a sweetAlert, since rails flash alerts won't display due to page cacheing.
