### ISSUE TITLE
About Face petition field should request city, not university

### ISSUE THREAD

**Issue by krcarlson** [EFForg/action-center-platform#801]
For people taking the About Face action, the field that currently says "University" should say "City." Also, the dropdown to filter the signatories says "Filter by University" It should say "Filter by City." 
https://act.eff.org/action/about-face
![Screen Shot 2020-01-15 at 9 46 07 AM](https://user-images.githubusercontent.com/8976353/72457778-300f4180-377c-11ea-99a8-1493beb16968.png)

![Screen Shot 2020-01-15 at 9 43 59 AM](https://user-images.githubusercontent.com/8976353/72457536-acedeb80-377b-11ea-9632-17812ed99d33.png)

**Comment by esoterik** [comment]
This is now fixed!
