### ISSUE TITLE
Create Dockerhub automated build from Github repo

### ISSUE THREAD

**Issue by Hainish** [EFForg/action-center-platform#82]
Dockerhub allows users to automatically build images from Github repos that contain a Dockerfile.  We should set this up for the action center.

**Comment by vbrown608** [comment]
Exists at https://hub.docker.com/r/efforg/action-center-platform/builds/ but doesn't appear to be building automatically - the most recent commit on master is from 10 days ago, most recent build is from 14 days ago.

**Comment by Hainish** [comment]
This is because it was set to auto-build from the `dockerize` branch.  I've changed it to the `master` branch and triggered a new build.

**Comment by vbrown608** [comment]
woohoo :whale:
